In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [10]:
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [13]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [16]:
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [18]:
import numpy as np
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [19]:
from numpy import random
x=random.rand()
print(x)

0.5382633729989342


In [21]:
x=random.randint(100 , size=(5))
print(x)

[89 16 34 20 29]


In [22]:
x=random.randint(100 , size=(3,5))
print(x)

[[86  9 89 18  4]
 [91 80 64 90 56]
 [30 32  6 55 90]]


In [23]:
x = random.choice([3,5,7,9])
print(x)

7
